//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IloopActiviyTransferVS_Net
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ILOOPEntities : DbContext
    {
        public ILOOPEntities()
            : base("name=ILOOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblActivity> tblActivity { get; set; }
        public virtual DbSet<tblHolidayRequest> tblHolidayRequest { get; set; }
        public virtual DbSet<tblOfficialHolidays> tblOfficialHolidays { get; set; }
    }
}
