//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IloopActiviyTransferVS_Net
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivity
    {
        public int intActivityID { get; set; }
        public Nullable<int> intActivityTypeID { get; set; }
        public Nullable<int> intProjectID { get; set; }
        public string strUserActivityComment { get; set; }
        public Nullable<int> intUserID { get; set; }
        public Nullable<System.DateTime> dtActivityDate { get; set; }
        public Nullable<int> intActivityDuration { get; set; }
        public Nullable<byte> intActivityStatus { get; set; }
        public Nullable<long> intActivityPDSTask { get; set; }
        public int intCustomerID { get; set; }
        public string strRejectComment { get; set; }
        public Nullable<int> intApproverID { get; set; }
        public Nullable<System.DateTime> dtCreateDate { get; set; }
    }
}
