//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IloopActiviyTransferVS_Net
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHolidayRequest
    {
        public int intHolidayRequestID { get; set; }
        public int intUserID { get; set; }
        public System.DateTime dtDateOfRequest { get; set; }
        public Nullable<System.DateTime> dtHolidayBeginDate { get; set; }
        public Nullable<System.DateTime> dtHolidayEndDate { get; set; }
        public int intTotalHours { get; set; }
        public int intHolidayTypeID { get; set; }
        public string strDetails { get; set; }
        public int dtWorkYear { get; set; }
        public int intHolidayApprovalTypeID { get; set; }
        public Nullable<int> intSuperVisorApprover { get; set; }
        public Nullable<System.DateTime> dtCreateDate { get; set; }
    }
}
