//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IloopActiviyTransferVS_Net
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOfficialHolidays
    {
        public int intOfficialHolidayID { get; set; }
        public System.DateTime dtHolidayDate { get; set; }
        public string EN { get; set; }
        public string FR { get; set; }
        public string TR { get; set; }
        public int Duration { get; set; }
    }
}
